### ISSUE TITLE
Nook Simple Touch Glowlight "There was a problem parsing the package"

### ISSUE THREAD

**Issue by AeliusSaionji** [Leszek111/ReLaunchX#10]
I have the old ReLaunch on this device. When I download the RelaunchX APK from f-droid, attmpting to install yields the error as stated in the title.

**Comment by jpawz** [comment]
This is old version, new one download from: https://www.mobileread.com/forums/showthread.php?t=284418

**Comment by AeliusSaionji** [comment]
Thanks, this works. First run gives me the error that my model isn't detected- I think you can safely add the "glowlight" models to your supported list. They're effectively just the NST with a light :)
