### ISSUE TITLE
No instructions for how to install

### ISSUE THREAD

**Issue by Narvey** [Leszek111/ReLaunchX#17]
I don't see this in the play store, I don't see any APK files under [releases](https://github.com/Leszek111/ReLaunchX/releases), there is no wiki... do we seriously have to compile this ourselves in order to use it?!

Also, your changelog is getting long enough that you should consider moving it out of the README.

**Comment by mahlzahn** [comment]
You find it in the F-Droid repository: https://f-droid.org/packages/com.gacode.relaunchx

**Comment by Leszek111** [comment]
added F-droid link
