### ISSUE TITLE
Add support for Kingrow K1 device

### ISSUE THREAD

**Issue by bjmc** [Leszek111/ReLaunchX#18]
Hello, I've recently gotten my hands on a [Kingrow K1](https://www.indiegogo.com/projects/kingrow-k1-the-healthy-phone-cares-your-eyes/x/13575994) e-ink Android phone, and I've been looking for a good launcher optimised for an e-ink display. ReLaunchX sounds fantastic, but when I try it on the 5.2" screen on the K1, it looks pretty awful.

(In fairness, ReLaunchX does show a big fat warning message that this is an unsupported device)

How much effort would be required to add support for the Kingrow K1? I'm willing to help out, but I have no experience in Android development.

**Comment by Leszek111** [comment]
Of course the warning's purpose is to set the expectations. I don't have all such devices, nor expertise in multi devices development.

Is it possible to share a screen shot? Pretty awful is too generic term.

**Comment by Leszek111** [comment]
BTW, I never paid much attention to the "bottom bar" of this legacy app as I was using it only on e-book reader to read pdfs. But yes, I'm also considering to get one of these e-ink phones, so one day I may revamp it altogether.

**Comment by bjmc** [comment]
I don't have the K1 with me right now, but I'll take a screenshot and post it here when I'm at home. Thanks for your help! I'm happy to test development builds, too.

**Comment by bjmc** [comment]
![Screenshot_20191129-192207](https://user-images.githubusercontent.com/328557/69887253-f5da0580-12dd-11ea-8473-4cfe0e8f2440.png)

**Comment by Leszek111** [comment]
ReLaunchX_2.1.5 let you customize the toolbar font size and the level of text details.
