### ISSUE TITLE
Versions later 1.3.1 doesn't work with Nook Simple Touch (Android 2.1)

### ISSUE THREAD

**Issue by huzilo** [Leszek111/ReLaunchX#6]
When I try to install version 1.3.2 or 2.0.0 I get

Parse Error
There is a problem parsing the package.

**Comment by Leszek111** [comment]
Fixed in 2.0.2. The new gradle 3.0.1 automatically uplift the minimum supported version to Gingerbread. For now the project will use previous gradle 2.3.1 as long as it is supported.
