### ISSUE TITLE
Old version in F-Droid

### ISSUE THREAD

**Issue by huzilo** [Leszek111/ReLaunchX#8]
In F-Droid repository is old version 2.0.0 of ReLaunchX which doesn't solve compatibility issues with Android 2.1 I reported.

**Comment by Leszek111** [comment]
Yes, I know but I am not F-Droid maintainer. Following F-Droid forum one can find out that the service is undergoing through serious maintenance.

I shared my local build on mobilerad.com if you, like many others, cannot build the app yourself.

Cheers

**Comment by huzilo** [comment]
@Leszek111 Emm... I searched for mobilerad but I found only radiologist viewer mobilerad.com/rtfs/ O.o

**Comment by Leszek111** [comment]
Sorry, it’s a typo. Actually the link to the forum, directly to the thread, is on F-droid

**Comment by huzilo** [comment]
It is. Thank you
